/*
###############################################################
#  Generated by:      Cadence Innovus 18.10-p002_1
#  OS:                Linux x86_64(Host ID c111-6.eecs.berkeley.edu)
#  Generated on:      Wed Jun  7 15:36:06 2023
#  Design:            fir
#  Command:           write_netlist /scratch/nk/asic_labs/lab1/sky130/build/par-rundir/fir.sim.v -top_module_first -top_module fir -exclude_leaf_cells -exclude_insts_of_cells { sky130_fd_sc_hd__tap_1 sky130_fd_sc_hd__tap_2 sky130_fd_sc_hd__tapvgnd_1 sky130_fd_sc_hd__tapvpwrvgnd_1 sky130_fd_sc_hd__fill_1 sky130_fd_sc_hd__fill_2 sky130_fd_sc_hd__fill_4 sky130_fd_sc_hd__fill_8 sky130_fd_sc_hd__diode_2 }
###############################################################
*/
module fir (
	clk, 
	rst, 
	In, 
	Out);
   input clk;
   input rst;
   input [3:0] In;
   output [15:0] Out;

   // Internal wires
   wire FE_PHN87_rst;
   wire FE_PHN86_In_1;
   wire FE_PHN85_rst;
   wire FE_PHN81_rst;
   wire FE_PHN52_rst;
   wire CTS_3;
   wire CTS_2;
   wire CTS_1;
   wire FE_OFN11_Out_0;
   wire FE_OFN10_Out_1;
   wire FE_OFN9_Out_2;
   wire FE_OFN8_Out_3;
   wire FE_OFN7_Out_4;
   wire FE_OFN6_Out_5;
   wire FE_OFN5_Out_6;
   wire FE_OFN4_Out_7;
   wire FE_RN_6;
   wire FE_RN_4;
   wire FE_RN_2;
   wire FE_OFN0_Out_10;
   wire [3:0] delay_chain0;
   wire [3:0] delay_chain1;
   wire [3:0] delay_chain2;
   wire [3:0] delay_chain3;
   wire [3:0] delay_chain4;
   wire UNCONNECTED6;
   wire UNCONNECTED7;
   wire UNCONNECTED8;
   wire UNCONNECTED9;
   wire UNCONNECTED10;
   wire UNCONNECTED11;
   wire UNCONNECTED12;

   assign Out[8] = FE_RN_2 ;
   assign FE_RN_6 = FE_RN_4 ;
   assign FE_RN_4 = FE_RN_2 ;
   assign Out[14] = Out[15] ;
   assign Out[12] = Out[13] ;
   assign Out[10] = Out[11] ;
   assign Out[9] = Out[11] ;

   sky130_fd_sc_hd__buf_4 FE_PHC87_rst (.A(FE_PHN52_rst),
	.X(FE_PHN87_rst));
   sky130_fd_sc_hd__clkbuf_1 FE_PHC86_In_1 (.A(In[1]),
	.X(FE_PHN86_In_1));
   sky130_fd_sc_hd__buf_6 FE_PHC85_rst (.A(FE_PHN87_rst),
	.X(FE_PHN85_rst));
   sky130_fd_sc_hd__buf_2 FE_PHC81_rst (.A(rst),
	.X(FE_PHN81_rst));
   sky130_fd_sc_hd__clkbuf_2 FE_PHC52_rst (.A(rst),
	.X(FE_PHN52_rst));
   sky130_fd_sc_hd__clkinv_8 CTS_ccl_a_inv_00006 (.A(CTS_3),
	.Y(CTS_2));
   sky130_fd_sc_hd__clkinv_4 CTS_ccl_a_inv_00004 (.A(CTS_3),
	.Y(CTS_1));
   sky130_fd_sc_hd__clkinv_16 CTS_ccl_a_inv_00009 (.A(clk),
	.Y(CTS_3));
   sky130_fd_sc_hd__buf_8 FE_OFC11_Out_0 (.A(FE_OFN11_Out_0),
	.X(Out[0]));
   sky130_fd_sc_hd__buf_8 FE_OFC10_Out_1 (.A(FE_OFN10_Out_1),
	.X(Out[1]));
   sky130_fd_sc_hd__buf_8 FE_OFC9_Out_2 (.A(FE_OFN9_Out_2),
	.X(Out[2]));
   sky130_fd_sc_hd__buf_8 FE_OFC8_Out_3 (.A(FE_OFN8_Out_3),
	.X(Out[3]));
   sky130_fd_sc_hd__buf_8 FE_OFC7_Out_4 (.A(FE_OFN7_Out_4),
	.X(Out[4]));
   sky130_fd_sc_hd__buf_8 FE_OFC6_Out_5 (.A(FE_OFN6_Out_5),
	.X(Out[5]));
   sky130_fd_sc_hd__buf_8 FE_OFC5_Out_6 (.A(FE_OFN5_Out_6),
	.X(Out[6]));
   sky130_fd_sc_hd__buf_8 FE_OFC4_Out_7 (.A(FE_OFN4_Out_7),
	.X(Out[7]));
   sky130_fd_sc_hd__buf_8 FE_OFC3_Out_10 (.A(Out[13]),
	.X(Out[11]));
   sky130_fd_sc_hd__buf_12 FE_OFC2_Out_10 (.A(Out[15]),
	.X(Out[13]));
   sky130_fd_sc_hd__buf_12 FE_OFC1_Out_10 (.A(FE_RN_6),
	.X(Out[15]));
   sky130_fd_sc_hd__buf_8 FE_OFC0_Out_10 (.A(FE_OFN0_Out_10),
	.X(FE_RN_2));
   addertree_NUM_INPUT_BITS4_NUM_OUTPUT_BITS16 add0 (.in0(delay_chain0),
	.in1(delay_chain1),
	.in2(delay_chain2),
	.in3(delay_chain3),
	.in4(delay_chain4),
	.Out({ FE_OFN0_Out_10,
		UNCONNECTED12,
		UNCONNECTED11,
		UNCONNECTED10,
		UNCONNECTED9,
		UNCONNECTED8,
		UNCONNECTED7,
		UNCONNECTED6,
		FE_OFN4_Out_7,
		FE_OFN5_Out_6,
		FE_OFN6_Out_5,
		FE_OFN7_Out_4,
		FE_OFN8_Out_3,
		FE_OFN9_Out_2,
		FE_OFN10_Out_1,
		FE_OFN11_Out_0 }));
   REGISTER_R_N4 delay_step0 (.q(delay_chain0),
	.d({ In[3],
		In[2],
		FE_PHN86_In_1,
		In[0] }),
	.rst(rst),
	.clk_clone1(CTS_1),
	.clk(CTS_2),
	.p1(FE_PHN52_rst),
	.p2(FE_PHN81_rst));
   REGISTER_R_N4_12 delay_step1 (.q(delay_chain1),
	.d(delay_chain0),
	.rst(FE_PHN81_rst),
	.clk_clone1(CTS_1),
	.clk(CTS_2),
	.p1(FE_PHN87_rst),
	.p2(FE_PHN85_rst));
   REGISTER_R_N4_11 delay_step2 (.q(delay_chain2),
	.d(delay_chain1),
	.rst(FE_PHN87_rst),
	.clk_clone1(CTS_1),
	.clk(CTS_2),
	.p1(FE_PHN85_rst));
   REGISTER_R_N4_10 delay_step3 (.q(delay_chain3),
	.d(delay_chain2),
	.rst(FE_PHN87_rst),
	.clk_clone1(CTS_1),
	.clk(CTS_2),
	.p1(FE_PHN85_rst));
   REGISTER_R_N4_9 delay_step4 (.q(delay_chain4),
	.d(delay_chain3),
	.rst(FE_PHN87_rst),
	.clk(CTS_2),
	.clk_clone1(CTS_1),
	.p1(FE_PHN85_rst));
endmodule

// Generated by Cadence Genus(TM) Synthesis Solution 19.15-s090_1
// Generated on: Jun  7 2023 14:22:24 PDT (Jun  7 2023 21:22:24 UTC)
// Verification Directory fv/fir 
module addertree_NUM_INPUT_BITS4_NUM_OUTPUT_BITS16 (
	in0, 
	in1, 
	in2, 
	in3, 
	in4, 
	Out);
   input [3:0] in0;
   input [3:0] in1;
   input [3:0] in2;
   input [3:0] in3;
   input [3:0] in4;
   output [15:0] Out;

   // Internal wires
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_36;
   wire n_38;
   wire n_40;
   wire n_42;
   wire n_44;

   sky130_fd_sc_hd__inv_2 g816 (.A(n_44),
	.Y(Out[15]));
   sky130_fd_sc_hd__fa_1 g817__2398 (.A(n_11),
	.B(n_24),
	.CIN(n_42),
	.COUT(n_44),
	.SUM(Out[7]));
   sky130_fd_sc_hd__fa_1 g818__5107 (.A(n_25),
	.B(n_32),
	.CIN(n_40),
	.COUT(n_42),
	.SUM(Out[6]));
   sky130_fd_sc_hd__fa_1 g819__6260 (.A(n_30),
	.B(n_33),
	.CIN(n_38),
	.COUT(n_40),
	.SUM(Out[5]));
   sky130_fd_sc_hd__fa_1 g820__4319 (.A(n_22),
	.B(n_31),
	.CIN(n_36),
	.COUT(n_38),
	.SUM(Out[4]));
   sky130_fd_sc_hd__fa_1 g821__8428 (.A(n_20),
	.B(n_23),
	.CIN(n_34),
	.COUT(n_36),
	.SUM(Out[3]));
   sky130_fd_sc_hd__fa_1 g822__5526 (.A(in0[2]),
	.B(n_26),
	.CIN(n_21),
	.COUT(n_34),
	.SUM(Out[2]));
   sky130_fd_sc_hd__inv_2 g823 (.A(n_29),
	.Y(n_33));
   sky130_fd_sc_hd__inv_2 g824 (.A(n_28),
	.Y(n_32));
   sky130_fd_sc_hd__fa_1 g825__6783 (.A(in1[2]),
	.B(n_18),
	.CIN(n_17),
	.COUT(n_30),
	.SUM(n_31));
   sky130_fd_sc_hd__fa_1 g826__3680 (.A(in1[3]),
	.B(n_15),
	.CIN(n_16),
	.COUT(n_28),
	.SUM(n_29));
   sky130_fd_sc_hd__fa_1 g827__1617 (.A(in0[1]),
	.B(in4[1]),
	.CIN(n_13),
	.COUT(n_26),
	.SUM(Out[1]));
   sky130_fd_sc_hd__ha_1 g828__2802 (.A(in2[2]),
	.B(n_14),
	.COUT(n_24),
	.SUM(n_25));
   sky130_fd_sc_hd__fa_1 g829__1705 (.A(in1[1]),
	.B(n_12),
	.CIN(n_19),
	.COUT(n_22),
	.SUM(n_23));
   sky130_fd_sc_hd__fa_1 g830__5122 (.A(in1[0]),
	.B(in3[0]),
	.CIN(in4[2]),
	.COUT(n_20),
	.SUM(n_21));
   sky130_fd_sc_hd__ha_1 g831__8246 (.A(in3[1]),
	.B(n_10),
	.COUT(n_18),
	.SUM(n_19));
   sky130_fd_sc_hd__a21o_1 g832__7098 (.A1(in2[0]),
	.A2(in3[2]),
	.B1(n_15),
	.X(n_17));
   sky130_fd_sc_hd__xnor2_1 g834__6131 (.A(in3[3]),
	.B(in2[1]),
	.Y(n_16));
   sky130_fd_sc_hd__nor2_1 g835__1881 (.A(in3[2]),
	.B(in2[0]),
	.Y(n_15));
   sky130_fd_sc_hd__nand2b_1 g836__5115 (.A_N(in2[1]),
	.B(in3[3]),
	.Y(n_14));
   sky130_fd_sc_hd__and2_1 g837__7482 (.A(in0[0]),
	.B(in4[0]),
	.X(n_13));
   sky130_fd_sc_hd__inv_2 g838 (.A(in0[3]),
	.Y(n_12));
   sky130_fd_sc_hd__inv_2 g839 (.A(in2[3]),
	.Y(n_11));
   sky130_fd_sc_hd__inv_1 g841 (.A(in4[3]),
	.Y(n_10));
   sky130_fd_sc_hd__xor2_1 g2__4733 (.A(in0[0]),
	.B(in4[0]),
	.X(Out[0]));
endmodule

module REGISTER_R_N4 (
	q, 
	d, 
	rst, 
	clk_clone1, 
	clk, 
	p1, 
	p2);
   output [3:0] q;
   input [3:0] d;
   input rst;
   input clk_clone1;
   input clk;
   input p1;
   input p2;

   // Internal wires
   wire FE_PHN84_In_1;
   wire FE_PHN60_n_3;
   wire FE_PHN55_n_0;
   wire FE_PHN54_n_2;
   wire FE_PHN53_n_1;
   wire FE_PHN35_n_3;
   wire FE_PHN34_n_0;
   wire FE_PHN33_n_1;
   wire FE_PHN32_n_2;
   wire FE_PHN25_n_1;
   wire FE_PHN18_n_2;
   wire FE_PHN16_n_0;
   wire FE_PHN13_n_3;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;

   sky130_fd_sc_hd__clkbuf_1 FE_PHC84_In_1 (.A(d[1]),
	.X(FE_PHN84_In_1));
   sky130_fd_sc_hd__dlygate4sd2_1 FE_PHC60_n_3 (.A(FE_PHN35_n_3),
	.X(FE_PHN60_n_3));
   sky130_fd_sc_hd__clkdlybuf4s18_2 FE_PHC55_n_0 (.A(FE_PHN34_n_0),
	.X(FE_PHN55_n_0));
   sky130_fd_sc_hd__clkdlybuf4s25_1 FE_PHC54_n_2 (.A(n_2),
	.X(FE_PHN54_n_2));
   sky130_fd_sc_hd__clkdlybuf4s25_2 FE_PHC53_n_1 (.A(n_1),
	.X(FE_PHN53_n_1));
   sky130_fd_sc_hd__clkdlybuf4s50_1 FE_PHC35_n_3 (.A(FE_PHN13_n_3),
	.X(FE_PHN35_n_3));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC34_n_0 (.A(FE_PHN16_n_0),
	.X(FE_PHN34_n_0));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC33_n_1 (.A(FE_PHN53_n_1),
	.X(FE_PHN33_n_1));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC32_n_2 (.A(FE_PHN54_n_2),
	.X(FE_PHN32_n_2));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC25_n_1 (.A(FE_PHN33_n_1),
	.X(FE_PHN25_n_1));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC18_n_2 (.A(FE_PHN32_n_2),
	.X(FE_PHN18_n_2));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC16_n_0 (.A(n_0),
	.X(FE_PHN16_n_0));
   sky130_fd_sc_hd__clkbuf_1 FE_PHC13_n_3 (.A(n_3),
	.X(FE_PHN13_n_3));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[3]  (.CLK(clk),
	.D(FE_PHN60_n_3),
	.Q(q[3]));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[2]  (.CLK(clk),
	.D(FE_PHN55_n_0),
	.Q(q[2]));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[0]  (.CLK(clk_clone1),
	.D(FE_PHN18_n_2),
	.Q(q[0]));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[1]  (.CLK(clk),
	.D(FE_PHN25_n_1),
	.Q(q[1]));
   sky130_fd_sc_hd__nor2b_1 g7__6161 (.A(rst),
	.B_N(d[3]),
	.Y(n_3));
   sky130_fd_sc_hd__nor2b_1 g8__9315 (.A(p1),
	.B_N(d[0]),
	.Y(n_2));
   sky130_fd_sc_hd__nor2b_1 g9__9945 (.A(p2),
	.B_N(FE_PHN84_In_1),
	.Y(n_1));
   sky130_fd_sc_hd__nor2b_1 g10__2883 (.A(rst),
	.B_N(d[2]),
	.Y(n_0));
endmodule

module REGISTER_R_N4_12 (
	q, 
	d, 
	rst, 
	clk_clone1, 
	clk, 
	p1, 
	p2);
   output [3:0] q;
   input [3:0] d;
   input rst;
   input clk_clone1;
   input clk;
   input p1;
   input p2;

   // Internal wires
   wire FE_PHN74_rst;
   wire FE_PHN71_n_3;
   wire FE_PHN70_n_1;
   wire FE_PHN57_n_2;
   wire FE_PHN51_n_3;
   wire FE_PHN50_n_0;
   wire FE_PHN49_n_1;
   wire FE_PHN48_n_2;
   wire FE_PHN31_n_3;
   wire FE_PHN23_n_2;
   wire FE_PHN17_n_0;
   wire FE_PHN12_n_1;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;

   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC74_rst (.A(rst),
	.X(FE_PHN74_rst));
   sky130_fd_sc_hd__clkdlybuf4s18_2 FE_PHC71_n_3 (.A(FE_PHN51_n_3),
	.X(FE_PHN71_n_3));
   sky130_fd_sc_hd__clkdlybuf4s18_2 FE_PHC70_n_1 (.A(n_1),
	.X(FE_PHN70_n_1));
   sky130_fd_sc_hd__clkdlybuf4s18_2 FE_PHC57_n_2 (.A(n_2),
	.X(FE_PHN57_n_2));
   sky130_fd_sc_hd__clkdlybuf4s25_2 FE_PHC51_n_3 (.A(n_3),
	.X(FE_PHN51_n_3));
   sky130_fd_sc_hd__clkdlybuf4s50_1 FE_PHC50_n_0 (.A(n_0),
	.X(FE_PHN50_n_0));
   sky130_fd_sc_hd__clkdlybuf4s50_1 FE_PHC49_n_1 (.A(FE_PHN70_n_1),
	.X(FE_PHN49_n_1));
   sky130_fd_sc_hd__clkdlybuf4s50_1 FE_PHC48_n_2 (.A(FE_PHN57_n_2),
	.X(FE_PHN48_n_2));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC31_n_3 (.A(FE_PHN71_n_3),
	.X(FE_PHN31_n_3));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC23_n_2 (.A(FE_PHN48_n_2),
	.X(FE_PHN23_n_2));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC17_n_0 (.A(FE_PHN50_n_0),
	.X(FE_PHN17_n_0));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC12_n_1 (.A(FE_PHN49_n_1),
	.X(FE_PHN12_n_1));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[3]  (.CLK(clk),
	.D(FE_PHN31_n_3),
	.Q(q[3]));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[2]  (.CLK(clk),
	.D(FE_PHN17_n_0),
	.Q(q[2]));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[0]  (.CLK(clk_clone1),
	.D(FE_PHN23_n_2),
	.Q(q[0]));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[1]  (.CLK(clk_clone1),
	.D(FE_PHN12_n_1),
	.Q(q[1]));
   sky130_fd_sc_hd__nor2b_1 g7__2346 (.A(FE_PHN74_rst),
	.B_N(d[3]),
	.Y(n_3));
   sky130_fd_sc_hd__nor2b_1 g8__1666 (.A(p1),
	.B_N(d[0]),
	.Y(n_2));
   sky130_fd_sc_hd__nor2b_1 g9__7410 (.A(p2),
	.B_N(d[1]),
	.Y(n_1));
   sky130_fd_sc_hd__nor2b_1 g10__6417 (.A(p2),
	.B_N(d[2]),
	.Y(n_0));
endmodule

module REGISTER_R_N4_11 (
	q, 
	d, 
	rst, 
	clk_clone1, 
	clk, 
	p1);
   output [3:0] q;
   input [3:0] d;
   input rst;
   input clk_clone1;
   input clk;
   input p1;

   // Internal wires
   wire FE_PHN68_n_3;
   wire FE_PHN67_n_1;
   wire FE_PHN64_n_2;
   wire FE_PHN59_n_0;
   wire FE_PHN46_n_0;
   wire FE_PHN43_n_3;
   wire FE_PHN40_n_2;
   wire FE_PHN39_n_1;
   wire FE_PHN29_n_1;
   wire FE_PHN21_n_0;
   wire FE_PHN15_n_3;
   wire FE_PHN14_n_2;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;

   sky130_fd_sc_hd__clkdlybuf4s18_2 FE_PHC68_n_3 (.A(n_3),
	.X(FE_PHN68_n_3));
   sky130_fd_sc_hd__clkdlybuf4s18_2 FE_PHC67_n_1 (.A(FE_PHN39_n_1),
	.X(FE_PHN67_n_1));
   sky130_fd_sc_hd__clkdlybuf4s18_2 FE_PHC64_n_2 (.A(n_2),
	.X(FE_PHN64_n_2));
   sky130_fd_sc_hd__clkdlybuf4s25_1 FE_PHC59_n_0 (.A(n_0),
	.X(FE_PHN59_n_0));
   sky130_fd_sc_hd__clkdlybuf4s50_1 FE_PHC46_n_0 (.A(FE_PHN59_n_0),
	.X(FE_PHN46_n_0));
   sky130_fd_sc_hd__clkdlybuf4s50_2 FE_PHC43_n_3 (.A(FE_PHN68_n_3),
	.X(FE_PHN43_n_3));
   sky130_fd_sc_hd__clkdlybuf4s50_2 FE_PHC40_n_2 (.A(FE_PHN64_n_2),
	.X(FE_PHN40_n_2));
   sky130_fd_sc_hd__clkdlybuf4s50_2 FE_PHC39_n_1 (.A(n_1),
	.X(FE_PHN39_n_1));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC29_n_1 (.A(FE_PHN67_n_1),
	.X(FE_PHN29_n_1));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC21_n_0 (.A(FE_PHN46_n_0),
	.X(FE_PHN21_n_0));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC15_n_3 (.A(FE_PHN43_n_3),
	.X(FE_PHN15_n_3));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC14_n_2 (.A(FE_PHN40_n_2),
	.X(FE_PHN14_n_2));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[3]  (.CLK(clk),
	.D(FE_PHN15_n_3),
	.Q(q[3]));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[2]  (.CLK(clk),
	.D(FE_PHN21_n_0),
	.Q(q[2]));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[0]  (.CLK(clk_clone1),
	.D(FE_PHN14_n_2),
	.Q(q[0]));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[1]  (.CLK(clk_clone1),
	.D(FE_PHN29_n_1),
	.Q(q[1]));
   sky130_fd_sc_hd__nor2b_1 g7__5477 (.A(p1),
	.B_N(d[3]),
	.Y(n_3));
   sky130_fd_sc_hd__nor2b_1 g8__2398 (.A(rst),
	.B_N(d[0]),
	.Y(n_2));
   sky130_fd_sc_hd__nor2b_1 g9__5107 (.A(rst),
	.B_N(d[1]),
	.Y(n_1));
   sky130_fd_sc_hd__nor2b_1 g10__6260 (.A(p1),
	.B_N(d[2]),
	.Y(n_0));
endmodule

module REGISTER_R_N4_10 (
	q, 
	d, 
	rst, 
	clk_clone1, 
	clk, 
	p1);
   output [3:0] q;
   input [3:0] d;
   input rst;
   input clk_clone1;
   input clk;
   input p1;

   // Internal wires
   wire FE_PHN65_n_1;
   wire FE_PHN63_n_0;
   wire FE_PHN62_n_2;
   wire FE_PHN56_n_3;
   wire FE_PHN45_n_3;
   wire FE_PHN42_n_1;
   wire FE_PHN38_n_2;
   wire FE_PHN37_n_0;
   wire FE_PHN30_n_3;
   wire FE_PHN27_n_0;
   wire FE_PHN26_n_1;
   wire FE_PHN22_n_2;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;

   sky130_fd_sc_hd__clkdlybuf4s18_2 FE_PHC65_n_1 (.A(n_1),
	.X(FE_PHN65_n_1));
   sky130_fd_sc_hd__clkdlybuf4s18_2 FE_PHC63_n_0 (.A(n_0),
	.X(FE_PHN63_n_0));
   sky130_fd_sc_hd__clkdlybuf4s18_2 FE_PHC62_n_2 (.A(n_2),
	.X(FE_PHN62_n_2));
   sky130_fd_sc_hd__clkdlybuf4s25_1 FE_PHC56_n_3 (.A(n_3),
	.X(FE_PHN56_n_3));
   sky130_fd_sc_hd__clkdlybuf4s50_1 FE_PHC45_n_3 (.A(FE_PHN56_n_3),
	.X(FE_PHN45_n_3));
   sky130_fd_sc_hd__clkdlybuf4s50_2 FE_PHC42_n_1 (.A(FE_PHN65_n_1),
	.X(FE_PHN42_n_1));
   sky130_fd_sc_hd__clkdlybuf4s50_2 FE_PHC38_n_2 (.A(FE_PHN62_n_2),
	.X(FE_PHN38_n_2));
   sky130_fd_sc_hd__clkdlybuf4s50_2 FE_PHC37_n_0 (.A(FE_PHN63_n_0),
	.X(FE_PHN37_n_0));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC30_n_3 (.A(FE_PHN45_n_3),
	.X(FE_PHN30_n_3));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC27_n_0 (.A(FE_PHN37_n_0),
	.X(FE_PHN27_n_0));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC26_n_1 (.A(FE_PHN42_n_1),
	.X(FE_PHN26_n_1));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC22_n_2 (.A(FE_PHN38_n_2),
	.X(FE_PHN22_n_2));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[3]  (.CLK(clk),
	.D(FE_PHN30_n_3),
	.Q(q[3]));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[2]  (.CLK(clk),
	.D(FE_PHN27_n_0),
	.Q(q[2]));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[0]  (.CLK(clk_clone1),
	.D(FE_PHN22_n_2),
	.Q(q[0]));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[1]  (.CLK(clk_clone1),
	.D(FE_PHN26_n_1),
	.Q(q[1]));
   sky130_fd_sc_hd__nor2b_1 g7__4319 (.A(p1),
	.B_N(d[3]),
	.Y(n_3));
   sky130_fd_sc_hd__nor2b_1 g8__8428 (.A(p1),
	.B_N(d[0]),
	.Y(n_2));
   sky130_fd_sc_hd__nor2b_1 g9__5526 (.A(rst),
	.B_N(d[1]),
	.Y(n_1));
   sky130_fd_sc_hd__nor2b_1 g10__6783 (.A(p1),
	.B_N(d[2]),
	.Y(n_0));
endmodule

module REGISTER_R_N4_9 (
	q, 
	d, 
	rst, 
	clk, 
	clk_clone1, 
	p1);
   output [3:0] q;
   input [3:0] d;
   input rst;
   input clk;
   input clk_clone1;
   input p1;

   // Internal wires
   wire FE_PHN69_n_0;
   wire FE_PHN66_n_2;
   wire FE_PHN61_n_1;
   wire FE_PHN58_n_3;
   wire FE_PHN47_n_3;
   wire FE_PHN44_n_0;
   wire FE_PHN41_n_2;
   wire FE_PHN36_n_1;
   wire FE_PHN28_n_1;
   wire FE_PHN24_n_0;
   wire FE_PHN20_n_2;
   wire FE_PHN19_n_3;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;

   sky130_fd_sc_hd__clkdlybuf4s18_2 FE_PHC69_n_0 (.A(FE_PHN44_n_0),
	.X(FE_PHN69_n_0));
   sky130_fd_sc_hd__clkdlybuf4s18_2 FE_PHC66_n_2 (.A(n_2),
	.X(FE_PHN66_n_2));
   sky130_fd_sc_hd__clkdlybuf4s18_2 FE_PHC61_n_1 (.A(FE_PHN61_n_1),
	.X(n_1));
   sky130_fd_sc_hd__clkdlybuf4s25_1 FE_PHC58_n_3 (.A(n_3),
	.X(FE_PHN58_n_3));
   sky130_fd_sc_hd__clkdlybuf4s50_1 FE_PHC47_n_3 (.A(FE_PHN58_n_3),
	.X(FE_PHN47_n_3));
   sky130_fd_sc_hd__clkdlybuf4s50_2 FE_PHC44_n_0 (.A(n_0),
	.X(FE_PHN44_n_0));
   sky130_fd_sc_hd__clkdlybuf4s50_2 FE_PHC41_n_2 (.A(FE_PHN66_n_2),
	.X(FE_PHN41_n_2));
   sky130_fd_sc_hd__clkdlybuf4s50_2 FE_PHC36_n_1 (.A(n_1),
	.X(FE_PHN36_n_1));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC28_n_1 (.A(FE_PHN36_n_1),
	.X(FE_PHN28_n_1));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC24_n_0 (.A(FE_PHN69_n_0),
	.X(FE_PHN24_n_0));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC20_n_2 (.A(FE_PHN41_n_2),
	.X(FE_PHN20_n_2));
   sky130_fd_sc_hd__dlygate4sd3_1 FE_PHC19_n_3 (.A(FE_PHN47_n_3),
	.X(FE_PHN19_n_3));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[3]  (.CLK(clk),
	.D(FE_PHN19_n_3),
	.Q(q[3]));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[2]  (.CLK(clk_clone1),
	.D(FE_PHN24_n_0),
	.Q(q[2]));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[0]  (.CLK(clk_clone1),
	.D(FE_PHN20_n_2),
	.Q(q[0]));
   sky130_fd_sc_hd__dfxtp_1 \q_reg[1]  (.CLK(clk_clone1),
	.D(FE_PHN28_n_1),
	.Q(q[1]));
   sky130_fd_sc_hd__nor2b_1 g7__3680 (.A(p1),
	.B_N(d[3]),
	.Y(n_3));
   sky130_fd_sc_hd__nor2b_1 g8__1617 (.A(p1),
	.B_N(d[0]),
	.Y(n_2));
   sky130_fd_sc_hd__nor2b_1 g9__2802 (.A(rst),
	.B_N(d[1]),
	.Y(FE_PHN61_n_1));
   sky130_fd_sc_hd__nor2b_1 g10__1705 (.A(rst),
	.B_N(d[2]),
	.Y(n_0));
endmodule

