/*
###############################################################
#  Generated by:      Cadence Innovus 18.10-p002_1
#  OS:                Linux x86_64(Host ID eda-5.EECS.Berkeley.EDU)
#  Generated on:      Fri Aug 28 19:50:07 2020
#  Design:            fir
#  Command:           write_netlist /home/cc/eecs151/fa20/staff/eecs151-taa/eecs151/lab2/build/par-rundir/fir.sim.v -top_module_first -top_module fir -exclude_leaf_cells -exclude_insts_of_cells { TAPCELL_ASAP7_75t_R TAPCELL_ASAP7_75t_L TAPCELL_ASAP7_75t_SL TAPCELL_ASAP7_75t_SRAM TAPCELL_WITH_FILLER_ASAP7_75t_R TAPCELL_WITH_FILLER_ASAP7_75t_L TAPCELL_WITH_FILLER_ASAP7_75t_SL TAPCELL_WITH_FILLER_ASAP7_75t_SRAM FILLER_ASAP7_75t_R FILLER_ASAP7_75t_L FILLER_ASAP7_75t_SL FILLER_ASAP7_75t_SRAM FILLERxp5_ASAP7_75t_R FILLERxp5_ASAP7_75t_L FILLERxp5_ASAP7_75t_SL FILLERxp5_ASAP7_75t_SRAM DECAPx1_ASAP7_75t_R DECAPx1_ASAP7_75t_L DECAPx1_ASAP7_75t_SL DECAPx1_ASAP7_75t_SRAM DECAPx2_ASAP7_75t_R DECAPx2_ASAP7_75t_L DECAPx2_ASAP7_75t_SL DECAPx2_ASAP7_75t_SRAM DECAPx4_ASAP7_75t_R DECAPx4_ASAP7_75t_L DECAPx4_ASAP7_75t_SL DECAPx4_ASAP7_75t_SRAM DECAPx6_ASAP7_75t_R DECAPx6_ASAP7_75t_L DECAPx6_ASAP7_75t_SL DECAPx6_ASAP7_75t_SRAM DECAPx10_ASAP7_75t_R DECAPx10_ASAP7_75t_L DECAPx10_ASAP7_75t_SL DECAPx10_ASAP7_75t_SRAM }
###############################################################
*/
module fir (
	clk, 
	In, 
	Out);
   input clk;
   input [3:0] In;
   output [15:0] Out;

   // Internal wires
   wire FE_PHN82_In_0;
   wire FE_PHN81_In_3;
   wire FE_PHN80_delay_chain3_2;
   wire FE_PHN79_In_0;
   wire FE_PHN78_In_2;
   wire FE_PHN77_In_1;
   wire FE_PHN76_delay_chain3_2;
   wire FE_PHN75_In_1;
   wire FE_PHN74_In_2;
   wire FE_PHN73_In_0;
   wire FE_PHN72_In_3;
   wire FE_PHN71_delay_chain0_2;
   wire FE_PHN70_delay_chain3_1;
   wire FE_PHN69_delay_chain1_0;
   wire FE_PHN68_delay_chain1_2;
   wire FE_PHN67_delay_chain0_3;
   wire FE_PHN66_delay_chain1_3;
   wire FE_PHN65_delay_chain1_1;
   wire FE_PHN64_delay_chain0_1;
   wire FE_PHN63_delay_chain2_1;
   wire FE_PHN62_delay_chain2_2;
   wire FE_PHN61_delay_chain3_0;
   wire FE_PHN60_delay_chain2_3;
   wire FE_PHN59_delay_chain2_0;
   wire FE_PHN58_delay_chain0_0;
   wire FE_PHN57_delay_chain3_3;
   wire FE_PHN56_In_2;
   wire FE_PHN55_In_0;
   wire FE_PHN54_In_1;
   wire FE_PHN53_delay_chain2_3;
   wire FE_PHN52_delay_chain3_0;
   wire FE_PHN51_delay_chain3_3;
   wire FE_PHN50_delay_chain2_0;
   wire FE_PHN49_delay_chain0_1;
   wire FE_PHN48_delay_chain2_1;
   wire FE_PHN47_delay_chain0_0;
   wire FE_PHN46_delay_chain2_2;
   wire FE_PHN45_delay_chain1_3;
   wire FE_PHN44_delay_chain3_2;
   wire FE_PHN43_delay_chain1_1;
   wire FE_PHN42_delay_chain0_2;
   wire FE_PHN41_delay_chain1_2;
   wire FE_PHN40_delay_chain1_0;
   wire FE_PHN39_delay_chain3_1;
   wire FE_PHN38_delay_chain0_3;
   wire FE_PHN37_In_3;
   wire FE_PHN36_In_1;
   wire FE_PHN35_In_3;
   wire FE_PHN34_In_0;
   wire FE_PHN33_In_2;
   wire FE_PHN32_delay_chain3_2;
   wire FE_PHN31_delay_chain3_3;
   wire FE_PHN30_delay_chain1_0;
   wire FE_PHN29_delay_chain2_0;
   wire FE_PHN28_delay_chain2_1;
   wire FE_PHN27_delay_chain3_1;
   wire FE_PHN26_delay_chain0_0;
   wire FE_PHN25_delay_chain2_3;
   wire FE_PHN24_delay_chain1_1;
   wire FE_PHN23_delay_chain2_2;
   wire FE_PHN22_delay_chain3_0;
   wire FE_PHN21_delay_chain1_2;
   wire FE_PHN20_delay_chain1_3;
   wire FE_PHN19_delay_chain0_3;
   wire FE_PHN18_delay_chain0_1;
   wire FE_PHN17_delay_chain0_2;
   wire FE_OFN16_Out_0;
   wire FE_OFN15_Out_1;
   wire FE_OFN14_Out_2;
   wire FE_OFN13_Out_3;
   wire FE_OFN12_Out_4;
   wire FE_OFN11_Out_5;
   wire FE_OFN10_Out_6;
   wire FE_OFN9_Out_7;
   wire FE_OFN1_Out_10;
   wire FE_OFN0_Out_10;
   wire [3:0] delay_chain0;
   wire [3:0] delay_chain1;
   wire [3:0] delay_chain2;
   wire [3:0] delay_chain3;
   wire [3:0] delay_chain4;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;

   BUFx2_ASAP7_75t_SL FE_PHC82_In_0 (.Y(FE_PHN82_In_0),
	.A(In[0]));
   BUFx2_ASAP7_75t_SL FE_PHC81_In_3 (.Y(FE_PHN81_In_3),
	.A(In[3]));
   BUFx2_ASAP7_75t_SL FE_PHC80_delay_chain3_2 (.Y(FE_PHN80_delay_chain3_2),
	.A(delay_chain3[2]));
   HB1xp67_ASAP7_75t_R FE_PHC79_In_0 (.Y(FE_PHN79_In_0),
	.A(FE_PHN82_In_0));
   BUFx2_ASAP7_75t_SL FE_PHC78_In_2 (.Y(FE_PHN78_In_2),
	.A(In[2]));
   HB1xp67_ASAP7_75t_R FE_PHC77_In_1 (.Y(FE_PHN77_In_1),
	.A(In[1]));
   HB2xp67_ASAP7_75t_SRAM FE_PHC76_delay_chain3_2 (.Y(FE_PHN76_delay_chain3_2),
	.A(FE_PHN80_delay_chain3_2));
   HB4xp67_ASAP7_75t_SRAM FE_PHC75_In_1 (.Y(FE_PHN75_In_1),
	.A(FE_PHN77_In_1));
   HB4xp67_ASAP7_75t_SRAM FE_PHC74_In_2 (.Y(FE_PHN74_In_2),
	.A(FE_PHN78_In_2));
   HB4xp67_ASAP7_75t_SRAM FE_PHC73_In_0 (.Y(FE_PHN73_In_0),
	.A(FE_PHN79_In_0));
   HB4xp67_ASAP7_75t_SRAM FE_PHC72_In_3 (.Y(FE_PHN72_In_3),
	.A(FE_PHN81_In_3));
   HB2xp67_ASAP7_75t_SRAM FE_PHC71_delay_chain0_2 (.Y(FE_PHN71_delay_chain0_2),
	.A(delay_chain0[2]));
   HB2xp67_ASAP7_75t_SRAM FE_PHC70_delay_chain3_1 (.Y(FE_PHN70_delay_chain3_1),
	.A(delay_chain3[1]));
   HB2xp67_ASAP7_75t_SRAM FE_PHC69_delay_chain1_0 (.Y(FE_PHN69_delay_chain1_0),
	.A(delay_chain1[0]));
   HB2xp67_ASAP7_75t_SRAM FE_PHC68_delay_chain1_2 (.Y(FE_PHN68_delay_chain1_2),
	.A(delay_chain1[2]));
   HB3xp67_ASAP7_75t_L FE_PHC67_delay_chain0_3 (.Y(FE_PHN67_delay_chain0_3),
	.A(FE_PHN38_delay_chain0_3));
   HB2xp67_ASAP7_75t_SRAM FE_PHC66_delay_chain1_3 (.Y(FE_PHN66_delay_chain1_3),
	.A(delay_chain1[3]));
   HB2xp67_ASAP7_75t_SRAM FE_PHC65_delay_chain1_1 (.Y(FE_PHN65_delay_chain1_1),
	.A(delay_chain1[1]));
   HB2xp67_ASAP7_75t_SRAM FE_PHC64_delay_chain0_1 (.Y(FE_PHN64_delay_chain0_1),
	.A(delay_chain0[1]));
   HB2xp67_ASAP7_75t_SRAM FE_PHC63_delay_chain2_1 (.Y(FE_PHN63_delay_chain2_1),
	.A(delay_chain2[1]));
   HB2xp67_ASAP7_75t_SRAM FE_PHC62_delay_chain2_2 (.Y(FE_PHN62_delay_chain2_2),
	.A(delay_chain2[2]));
   HB2xp67_ASAP7_75t_SRAM FE_PHC61_delay_chain3_0 (.Y(FE_PHN61_delay_chain3_0),
	.A(delay_chain3[0]));
   HB2xp67_ASAP7_75t_SRAM FE_PHC60_delay_chain2_3 (.Y(FE_PHN60_delay_chain2_3),
	.A(delay_chain2[3]));
   HB2xp67_ASAP7_75t_SRAM FE_PHC59_delay_chain2_0 (.Y(FE_PHN59_delay_chain2_0),
	.A(delay_chain2[0]));
   HB2xp67_ASAP7_75t_SRAM FE_PHC58_delay_chain0_0 (.Y(FE_PHN58_delay_chain0_0),
	.A(delay_chain0[0]));
   HB3xp67_ASAP7_75t_R FE_PHC57_delay_chain3_3 (.Y(FE_PHN57_delay_chain3_3),
	.A(delay_chain3[3]));
   HB4xp67_ASAP7_75t_SRAM FE_PHC56_In_2 (.Y(FE_PHN56_In_2),
	.A(FE_PHN74_In_2));
   HB4xp67_ASAP7_75t_SRAM FE_PHC55_In_0 (.Y(FE_PHN55_In_0),
	.A(FE_PHN73_In_0));
   HB4xp67_ASAP7_75t_SRAM FE_PHC54_In_1 (.Y(FE_PHN54_In_1),
	.A(FE_PHN75_In_1));
   HB4xp67_ASAP7_75t_SRAM FE_PHC53_delay_chain2_3 (.Y(FE_PHN53_delay_chain2_3),
	.A(FE_PHN60_delay_chain2_3));
   HB4xp67_ASAP7_75t_SRAM FE_PHC52_delay_chain3_0 (.Y(FE_PHN52_delay_chain3_0),
	.A(FE_PHN61_delay_chain3_0));
   HB4xp67_ASAP7_75t_SRAM FE_PHC51_delay_chain3_3 (.Y(FE_PHN51_delay_chain3_3),
	.A(FE_PHN57_delay_chain3_3));
   HB4xp67_ASAP7_75t_SRAM FE_PHC50_delay_chain2_0 (.Y(FE_PHN50_delay_chain2_0),
	.A(FE_PHN59_delay_chain2_0));
   HB4xp67_ASAP7_75t_SRAM FE_PHC49_delay_chain0_1 (.Y(FE_PHN49_delay_chain0_1),
	.A(FE_PHN64_delay_chain0_1));
   HB4xp67_ASAP7_75t_SRAM FE_PHC48_delay_chain2_1 (.Y(FE_PHN48_delay_chain2_1),
	.A(FE_PHN63_delay_chain2_1));
   HB4xp67_ASAP7_75t_SRAM FE_PHC47_delay_chain0_0 (.Y(FE_PHN47_delay_chain0_0),
	.A(FE_PHN58_delay_chain0_0));
   HB4xp67_ASAP7_75t_SRAM FE_PHC46_delay_chain2_2 (.Y(FE_PHN46_delay_chain2_2),
	.A(FE_PHN62_delay_chain2_2));
   HB4xp67_ASAP7_75t_SRAM FE_PHC45_delay_chain1_3 (.Y(FE_PHN45_delay_chain1_3),
	.A(FE_PHN66_delay_chain1_3));
   HB4xp67_ASAP7_75t_SRAM FE_PHC44_delay_chain3_2 (.Y(FE_PHN44_delay_chain3_2),
	.A(FE_PHN76_delay_chain3_2));
   HB4xp67_ASAP7_75t_SRAM FE_PHC43_delay_chain1_1 (.Y(FE_PHN43_delay_chain1_1),
	.A(FE_PHN65_delay_chain1_1));
   HB4xp67_ASAP7_75t_SRAM FE_PHC42_delay_chain0_2 (.Y(FE_PHN42_delay_chain0_2),
	.A(FE_PHN71_delay_chain0_2));
   HB4xp67_ASAP7_75t_SRAM FE_PHC41_delay_chain1_2 (.Y(FE_PHN41_delay_chain1_2),
	.A(FE_PHN68_delay_chain1_2));
   HB4xp67_ASAP7_75t_SRAM FE_PHC40_delay_chain1_0 (.Y(FE_PHN40_delay_chain1_0),
	.A(FE_PHN69_delay_chain1_0));
   HB4xp67_ASAP7_75t_SRAM FE_PHC39_delay_chain3_1 (.Y(FE_PHN39_delay_chain3_1),
	.A(FE_PHN70_delay_chain3_1));
   HB4xp67_ASAP7_75t_SRAM FE_PHC38_delay_chain0_3 (.Y(FE_PHN38_delay_chain0_3),
	.A(delay_chain0[3]));
   HB4xp67_ASAP7_75t_SRAM FE_PHC37_In_3 (.Y(FE_PHN37_In_3),
	.A(FE_PHN72_In_3));
   HB4xp67_ASAP7_75t_SRAM FE_PHC36_In_1 (.Y(FE_PHN36_In_1),
	.A(FE_PHN54_In_1));
   HB4xp67_ASAP7_75t_SRAM FE_PHC35_In_3 (.Y(FE_PHN35_In_3),
	.A(FE_PHN37_In_3));
   HB4xp67_ASAP7_75t_SRAM FE_PHC34_In_0 (.Y(FE_PHN34_In_0),
	.A(FE_PHN55_In_0));
   HB4xp67_ASAP7_75t_SRAM FE_PHC33_In_2 (.Y(FE_PHN33_In_2),
	.A(FE_PHN56_In_2));
   HB4xp67_ASAP7_75t_SRAM FE_PHC32_delay_chain3_2 (.Y(FE_PHN32_delay_chain3_2),
	.A(FE_PHN44_delay_chain3_2));
   HB4xp67_ASAP7_75t_SRAM FE_PHC31_delay_chain3_3 (.Y(FE_PHN31_delay_chain3_3),
	.A(FE_PHN51_delay_chain3_3));
   HB4xp67_ASAP7_75t_SRAM FE_PHC30_delay_chain1_0 (.Y(FE_PHN30_delay_chain1_0),
	.A(FE_PHN40_delay_chain1_0));
   HB4xp67_ASAP7_75t_SRAM FE_PHC29_delay_chain2_0 (.Y(FE_PHN29_delay_chain2_0),
	.A(FE_PHN50_delay_chain2_0));
   HB4xp67_ASAP7_75t_SRAM FE_PHC28_delay_chain2_1 (.Y(FE_PHN28_delay_chain2_1),
	.A(FE_PHN48_delay_chain2_1));
   HB4xp67_ASAP7_75t_SRAM FE_PHC27_delay_chain3_1 (.Y(FE_PHN27_delay_chain3_1),
	.A(FE_PHN39_delay_chain3_1));
   HB4xp67_ASAP7_75t_SRAM FE_PHC26_delay_chain0_0 (.Y(FE_PHN26_delay_chain0_0),
	.A(FE_PHN47_delay_chain0_0));
   HB4xp67_ASAP7_75t_SRAM FE_PHC25_delay_chain2_3 (.Y(FE_PHN25_delay_chain2_3),
	.A(FE_PHN53_delay_chain2_3));
   HB4xp67_ASAP7_75t_SRAM FE_PHC24_delay_chain1_1 (.Y(FE_PHN24_delay_chain1_1),
	.A(FE_PHN43_delay_chain1_1));
   HB4xp67_ASAP7_75t_SRAM FE_PHC23_delay_chain2_2 (.Y(FE_PHN23_delay_chain2_2),
	.A(FE_PHN46_delay_chain2_2));
   HB4xp67_ASAP7_75t_SRAM FE_PHC22_delay_chain3_0 (.Y(FE_PHN22_delay_chain3_0),
	.A(FE_PHN52_delay_chain3_0));
   HB4xp67_ASAP7_75t_SRAM FE_PHC21_delay_chain1_2 (.Y(FE_PHN21_delay_chain1_2),
	.A(FE_PHN41_delay_chain1_2));
   HB4xp67_ASAP7_75t_SRAM FE_PHC20_delay_chain1_3 (.Y(FE_PHN20_delay_chain1_3),
	.A(FE_PHN45_delay_chain1_3));
   HB4xp67_ASAP7_75t_SRAM FE_PHC19_delay_chain0_3 (.Y(FE_PHN19_delay_chain0_3),
	.A(FE_PHN67_delay_chain0_3));
   HB4xp67_ASAP7_75t_SRAM FE_PHC18_delay_chain0_1 (.Y(FE_PHN18_delay_chain0_1),
	.A(FE_PHN49_delay_chain0_1));
   HB4xp67_ASAP7_75t_SRAM FE_PHC17_delay_chain0_2 (.Y(FE_PHN17_delay_chain0_2),
	.A(FE_PHN42_delay_chain0_2));
   BUFx24_ASAP7_75t_SL FE_OFC16_Out_0 (.Y(Out[0]),
	.A(FE_OFN16_Out_0));
   BUFx24_ASAP7_75t_SL FE_OFC15_Out_1 (.Y(Out[1]),
	.A(FE_OFN15_Out_1));
   BUFx24_ASAP7_75t_SL FE_OFC14_Out_2 (.Y(Out[2]),
	.A(FE_OFN14_Out_2));
   BUFx24_ASAP7_75t_SL FE_OFC13_Out_3 (.Y(Out[3]),
	.A(FE_OFN13_Out_3));
   BUFx24_ASAP7_75t_SL FE_OFC12_Out_4 (.Y(Out[4]),
	.A(FE_OFN12_Out_4));
   BUFx24_ASAP7_75t_SL FE_OFC11_Out_5 (.Y(Out[5]),
	.A(FE_OFN11_Out_5));
   BUFx24_ASAP7_75t_SL FE_OFC10_Out_6 (.Y(Out[6]),
	.A(FE_OFN10_Out_6));
   BUFx24_ASAP7_75t_SL FE_OFC9_Out_7 (.Y(Out[7]),
	.A(FE_OFN9_Out_7));
   BUFx24_ASAP7_75t_SL FE_OFC8_Out_10 (.Y(Out[10]),
	.A(FE_OFN1_Out_10));
   BUFx24_ASAP7_75t_SL FE_OFC7_Out_10 (.Y(Out[9]),
	.A(FE_OFN1_Out_10));
   BUFx24_ASAP7_75t_SL FE_OFC6_Out_10 (.Y(Out[8]),
	.A(FE_OFN1_Out_10));
   BUFx24_ASAP7_75t_SL FE_OFC5_Out_10 (.Y(Out[11]),
	.A(FE_OFN1_Out_10));
   BUFx24_ASAP7_75t_SL FE_OFC4_Out_10 (.Y(Out[12]),
	.A(FE_OFN1_Out_10));
   BUFx24_ASAP7_75t_SL FE_OFC3_Out_10 (.Y(Out[13]),
	.A(FE_OFN1_Out_10));
   BUFx24_ASAP7_75t_SL FE_OFC2_Out_10 (.Y(Out[14]),
	.A(FE_OFN1_Out_10));
   BUFx24_ASAP7_75t_SL FE_OFC1_Out_10 (.Y(Out[15]),
	.A(FE_OFN1_Out_10));
   BUFx2_ASAP7_75t_SL FE_OFC0_Out_10 (.Y(FE_OFN1_Out_10),
	.A(FE_OFN0_Out_10));
   addertree_NUM_INPUT_BITS4_NUM_OUTPUT_BITS16 add0 (.in0(delay_chain0),
	.in1(delay_chain1),
	.in2(delay_chain2),
	.in3(delay_chain3),
	.in4(delay_chain4),
	.Out({ FE_OFN0_Out_10,
		UNCONNECTED5,
		UNCONNECTED4,
		UNCONNECTED3,
		UNCONNECTED2,
		UNCONNECTED1,
		UNCONNECTED0,
		UNCONNECTED,
		FE_OFN9_Out_7,
		FE_OFN10_Out_6,
		FE_OFN11_Out_5,
		FE_OFN12_Out_4,
		FE_OFN13_Out_3,
		FE_OFN14_Out_2,
		FE_OFN15_Out_1,
		FE_OFN16_Out_0 }));
   DFFHQx4_ASAP7_75t_L \delay_chain4_reg[3]  (.Q(delay_chain4[3]),
	.CLK(clk),
	.D(FE_PHN31_delay_chain3_3));
   DFFHQx4_ASAP7_75t_SL \delay_chain4_reg[0]  (.Q(delay_chain4[0]),
	.CLK(clk),
	.D(FE_PHN22_delay_chain3_0));
   DFFHQx4_ASAP7_75t_L \delay_chain4_reg[2]  (.Q(delay_chain4[2]),
	.CLK(clk),
	.D(FE_PHN32_delay_chain3_2));
   DFFHQx4_ASAP7_75t_SL \delay_chain4_reg[1]  (.Q(delay_chain4[1]),
	.CLK(clk),
	.D(FE_PHN27_delay_chain3_1));
   DFFHQx4_ASAP7_75t_SL \delay_chain3_reg[0]  (.Q(delay_chain3[0]),
	.CLK(clk),
	.D(FE_PHN29_delay_chain2_0));
   DFFHQx4_ASAP7_75t_SL \delay_chain3_reg[2]  (.Q(delay_chain3[2]),
	.CLK(clk),
	.D(FE_PHN23_delay_chain2_2));
   DFFHQx4_ASAP7_75t_SL \delay_chain3_reg[3]  (.Q(delay_chain3[3]),
	.CLK(clk),
	.D(FE_PHN25_delay_chain2_3));
   DFFHQx4_ASAP7_75t_SL \delay_chain3_reg[1]  (.Q(delay_chain3[1]),
	.CLK(clk),
	.D(FE_PHN28_delay_chain2_1));
   DFFHQx4_ASAP7_75t_SL \delay_chain2_reg[1]  (.Q(delay_chain2[1]),
	.CLK(clk),
	.D(FE_PHN24_delay_chain1_1));
   DFFHQx4_ASAP7_75t_SL \delay_chain2_reg[3]  (.Q(delay_chain2[3]),
	.CLK(clk),
	.D(FE_PHN20_delay_chain1_3));
   DFFHQx4_ASAP7_75t_SL \delay_chain2_reg[2]  (.Q(delay_chain2[2]),
	.CLK(clk),
	.D(FE_PHN21_delay_chain1_2));
   DFFHQx4_ASAP7_75t_SL \delay_chain2_reg[0]  (.Q(delay_chain2[0]),
	.CLK(clk),
	.D(FE_PHN30_delay_chain1_0));
   DFFHQx4_ASAP7_75t_SL \delay_chain1_reg[3]  (.Q(delay_chain1[3]),
	.CLK(clk),
	.D(FE_PHN19_delay_chain0_3));
   DFFHQx4_ASAP7_75t_SL \delay_chain1_reg[2]  (.Q(delay_chain1[2]),
	.CLK(clk),
	.D(FE_PHN17_delay_chain0_2));
   DFFHQx4_ASAP7_75t_SL \delay_chain1_reg[0]  (.Q(delay_chain1[0]),
	.CLK(clk),
	.D(FE_PHN26_delay_chain0_0));
   DFFHQx4_ASAP7_75t_SL \delay_chain1_reg[1]  (.Q(delay_chain1[1]),
	.CLK(clk),
	.D(FE_PHN18_delay_chain0_1));
   DFFHQx4_ASAP7_75t_SL \delay_chain0_reg[1]  (.Q(delay_chain0[1]),
	.CLK(clk),
	.D(FE_PHN36_In_1));
   DFFHQx4_ASAP7_75t_SL \delay_chain0_reg[2]  (.Q(delay_chain0[2]),
	.CLK(clk),
	.D(FE_PHN33_In_2));
   DFFHQx4_ASAP7_75t_SL \delay_chain0_reg[3]  (.Q(delay_chain0[3]),
	.CLK(clk),
	.D(FE_PHN35_In_3));
   DFFHQx4_ASAP7_75t_SL \delay_chain0_reg[0]  (.Q(delay_chain0[0]),
	.CLK(clk),
	.D(FE_PHN34_In_0));
endmodule

// Generated by Cadence Genus(TM) Synthesis Solution 19.11-s087_1
// Generated on: Aug 28 2020 19:43:50 PDT (Aug 29 2020 02:43:50 UTC)
// Verification Directory fv/fir 
module addertree_NUM_INPUT_BITS4_NUM_OUTPUT_BITS16 (
	in0, 
	in1, 
	in2, 
	in3, 
	in4, 
	Out);
   input [3:0] in0;
   input [3:0] in1;
   input [3:0] in2;
   input [3:0] in3;
   input [3:0] in4;
   output [15:0] Out;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_61;
   wire n_63;
   wire n_65;
   wire n_67;

   AOI21xp33_ASAP7_75t_SL g816__2398 (.Y(Out[15]),
	.A1(n_67),
	.A2(n_30),
	.B(n_28));
   XNOR2xp5_ASAP7_75t_SRAM g817__5107 (.Y(Out[7]),
	.A(n_35),
	.B(n_67));
   OAI21xp33_ASAP7_75t_SL g818__6260 (.Y(n_67),
	.A1(n_40),
	.A2(n_65),
	.B(n_41));
   XNOR2xp5_ASAP7_75t_SRAM g819__4319 (.Y(Out[6]),
	.A(n_53),
	.B(n_65));
   AOI21xp33_ASAP7_75t_SL g820__8428 (.Y(n_65),
	.A1(n_63),
	.A2(n_55),
	.B(n_51));
   XNOR2xp5_ASAP7_75t_SRAM g821__5526 (.Y(Out[5]),
	.A(n_58),
	.B(n_63));
   OAI21xp33_ASAP7_75t_SL g822__6783 (.Y(n_63),
	.A1(n_1),
	.A2(n_61),
	.B(n_50));
   XNOR2xp5_ASAP7_75t_SRAM g823__3680 (.Y(Out[4]),
	.A(n_56),
	.B(n_61));
   AOI21xp33_ASAP7_75t_SL g824__1617 (.Y(n_61),
	.A1(n_57),
	.A2(n_45),
	.B(n_43));
   XNOR2xp5_ASAP7_75t_SRAM g825__2802 (.Y(Out[3]),
	.A(n_54),
	.B(n_57));
   XNOR2xp5_ASAP7_75t_SRAM g826__1705 (.Y(Out[2]),
	.A(n_27),
	.B(n_48));
   NAND2xp5_ASAP7_75t_R g827__5122 (.Y(n_58),
	.A(n_52),
	.B(n_55));
   NOR2xp33_ASAP7_75t_R g828__8246 (.Y(n_56),
	.A(n_1),
	.B(n_49));
   AO21x1_ASAP7_75t_SRAM g829__7098 (.Y(n_57),
	.A1(n_27),
	.A2(n_39),
	.B(n_47));
   NAND2xp5_ASAP7_75t_R g830__6131 (.Y(n_54),
	.A(n_44),
	.B(n_45));
   NAND2xp5_ASAP7_75t_R g831__1881 (.Y(n_55),
	.A(n_34),
	.B(n_0));
   NOR2xp33_ASAP7_75t_R g832__5115 (.Y(n_53),
	.A(n_42),
	.B(n_40));
   INVx1_ASAP7_75t_SL g833 (.Y(n_52),
	.A(n_51));
   INVx1_ASAP7_75t_SL g834 (.Y(n_50),
	.A(n_49));
   NAND2xp5_ASAP7_75t_R g836__7482 (.Y(n_48),
	.A(n_46),
	.B(n_39));
   NOR2xp33_ASAP7_75t_R g837__4733 (.Y(n_51),
	.A(n_34),
	.B(n_0));
   NOR2xp33_ASAP7_75t_R g838__6161 (.Y(n_49),
	.A(n_31),
	.B(n_38));
   INVx1_ASAP7_75t_SL g839 (.Y(n_47),
	.A(n_46));
   INVx1_ASAP7_75t_SL g840 (.Y(n_44),
	.A(n_43));
   INVx1_ASAP7_75t_SL g841 (.Y(n_42),
	.A(n_41));
   NAND2xp5_ASAP7_75t_R g842__9315 (.Y(n_46),
	.A(in0[2]),
	.B(n_32));
   NAND2xp5_ASAP7_75t_R g843__9945 (.Y(n_45),
	.A(n_26),
	.B(n_37));
   NOR2xp33_ASAP7_75t_R g844__2883 (.Y(n_43),
	.A(n_26),
	.B(n_37));
   NAND2xp5_ASAP7_75t_R g845__2346 (.Y(n_41),
	.A(n_25),
	.B(n_33));
   NOR2xp33_ASAP7_75t_R g848__1666 (.Y(n_40),
	.A(n_25),
	.B(n_33));
   OR2x2_ASAP7_75t_SRAM g849__7410 (.Y(n_39),
	.A(in0[2]),
	.B(n_32));
   XNOR2xp5_ASAP7_75t_SRAM g850__6417 (.Y(n_38),
	.A(n_20),
	.B(n_24));
   XNOR2xp5_ASAP7_75t_SRAM g851__5477 (.Y(Out[1]),
	.A(n_6),
	.B(n_18));
   NAND2xp5_ASAP7_75t_R g852__2398 (.Y(n_35),
	.A(n_29),
	.B(n_30));
   XNOR2xp5_ASAP7_75t_SRAM g853__5107 (.Y(n_37),
	.A(n_15),
	.B(n_16));
   MAJIxp5_ASAP7_75t_SRAM g855__6260 (.Y(n_34),
	.A(n_21),
	.B(in1[2]),
	.C(n_13));
   MAJIxp5_ASAP7_75t_SRAM g856__4319 (.Y(n_33),
	.A(n_17),
	.B(in1[3]),
	.C(n_10));
   XNOR2xp5_ASAP7_75t_SRAM g857__8428 (.Y(n_32),
	.A(in1[0]),
	.B(n_14));
   MAJIxp5_ASAP7_75t_SRAM g858__5526 (.Y(n_31),
	.A(n_16),
	.B(in1[1]),
	.C(n_3));
   INVx1_ASAP7_75t_SL g859 (.Y(n_29),
	.A(n_28));
   NAND2xp5_ASAP7_75t_R g860__6783 (.Y(n_30),
	.A(in2[3]),
	.B(n_22));
   NOR2xp33_ASAP7_75t_R g861__3680 (.Y(n_28),
	.A(in2[3]),
	.B(n_22));
   OAI21xp33_ASAP7_75t_SL g862__1617 (.Y(n_27),
	.A1(n_7),
	.A2(n_6),
	.B(n_8));
   MAJIxp5_ASAP7_75t_SRAM g863__2802 (.Y(n_26),
	.A(in1[0]),
	.B(in4[2]),
	.C(in3[0]));
   XNOR2xp5_ASAP7_75t_SRAM g864__1705 (.Y(n_24),
	.A(in1[2]),
	.B(n_13));
   XNOR2xp5_ASAP7_75t_SRAM g865__5122 (.Y(n_25),
	.A(in2[2]),
	.B(n_11));
   XOR2xp5_ASAP7_75t_SRAM g866__8246 (.Y(n_23),
	.A(in1[3]),
	.B(n_10));
   INVx1_ASAP7_75t_SL g867 (.Y(n_21),
	.A(n_20));
   OA21x2_ASAP7_75t_SRAM g868__7098 (.Y(Out[0]),
	.A1(in4[0]),
	.A2(in0[0]),
	.B(n_6));
   NAND2xp5_ASAP7_75t_R g869__6131 (.Y(n_22),
	.A(in2[2]),
	.B(n_12));
   NOR2xp33_ASAP7_75t_R g870__1881 (.Y(n_18),
	.A(n_7),
	.B(n_9));
   AOI21xp33_ASAP7_75t_SL g871__5115 (.Y(n_20),
	.A1(in2[0]),
	.A2(in3[2]),
	.B(n_10));
   XNOR2xp5_ASAP7_75t_SRAM g873__7482 (.Y(n_15),
	.A(in0[3]),
	.B(in1[1]));
   XNOR2xp5_ASAP7_75t_SRAM g874__4733 (.Y(n_14),
	.A(in4[2]),
	.B(in3[0]));
   AOI21xp33_ASAP7_75t_SL g875__6161 (.Y(n_17),
	.A1(n_5),
	.A2(in2[1]),
	.B(n_11));
   XNOR2xp5_ASAP7_75t_SRAM g876__9315 (.Y(n_16),
	.A(in4[3]),
	.B(in3[1]));
   INVx1_ASAP7_75t_SL g877 (.Y(n_12),
	.A(n_11));
   NOR2xp33_ASAP7_75t_R g878__9945 (.Y(n_13),
	.A(in4[3]),
	.B(n_4));
   NOR2xp33_ASAP7_75t_R g879__2883 (.Y(n_11),
	.A(in2[1]),
	.B(n_5));
   NOR2xp33_ASAP7_75t_R g880__2346 (.Y(n_10),
	.A(in3[2]),
	.B(in2[0]));
   INVx1_ASAP7_75t_SL g881 (.Y(n_9),
	.A(n_8));
   NAND2xp5_ASAP7_75t_R g882__1666 (.Y(n_8),
	.A(in4[1]),
	.B(in0[1]));
   NOR2xp33_ASAP7_75t_R g883__7410 (.Y(n_7),
	.A(in4[1]),
	.B(in0[1]));
   NAND2xp5_ASAP7_75t_R g884__6417 (.Y(n_6),
	.A(in4[0]),
	.B(in0[0]));
   INVx1_ASAP7_75t_SL g885 (.Y(n_5),
	.A(in3[3]));
   INVx1_ASAP7_75t_SL g886 (.Y(n_4),
	.A(in3[1]));
   INVx1_ASAP7_75t_SL g887 (.Y(n_3),
	.A(in0[3]));
   AND2x2_ASAP7_75t_SL g2__5477 (.Y(n_1),
	.A(n_31),
	.B(n_38));
   XOR2xp5_ASAP7_75t_SL g888__2398 (.Y(n_0),
	.A(n_17),
	.B(n_23));
endmodule

